language: go
os:
  - linux
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  # Coverage
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  # Check format and code cleanliness
  - gofmt -l ./ | grep -v vendor | wc -l | grep -q 0
  - go vet -v
  # Run Tests
  - make tests clean
after_success:
  - goveralls -coverprofile=coverage/coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
