language: go
go:
  - 1.14.1
os:
  - linux
script:
  - gofmt -l ./ | grep -v vendor | wc -l | grep -q 0
  - go vet -v ./...
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - docker-compose up --build -d 
