language: go
go:
  - 1.14.1
os:
  - linux
before_script:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go mod tidy
script:
  - gofmt -l ./ | grep -v vendor | wc -l | grep -q 0
  - go vet -v ./...
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - docker-compose up --build -d 
