version: '3.8'
services:
  healthchecks-example:
    build: .
    ports:
      - 443:8443
      - 80:8080
    environment:
      - "ENABLE_TLS=false"
      - "DEBUG=true"
      - "LISTEN_ADDR=0.0.0.0:8080"
      - "DB_SERVER=redis:6379"
    depends_on:
      - redis
    secrets:
      - password
  redis:
    image: bitnami/redis:latest
    environment:
      - "REDIS_PASSWORD=example"
secrets:
  password:
    file: ./secret.txt
