version: '3.8'
services:
  go-quick:
    build: .
    ports:
      - 443:8443
      - 80:8080
    environment:
      - "APP_ENABLE_TLS=false"
      - "APP_LISTEN_ADDR=0.0.0.0:8080"
      - "APP_DB_SERVER=redis:6379"
      - "APP_USE_CONSUL=true"
      - "APP_CONSUL_ADDR=consul:8500"
      - "APP_CONSUL_KEYS_PREFIX=go-quick/config"
      - "CONSUL_HTTP_ADDR=consul:8500"
      - "CONSUL_HTTP_SSL=false"
    depends_on:
      - redis
      - consul
      - consulator
    secrets:
      - password
  redis:
    image: bitnami/redis:latest
    environment:
      - "REDIS_PASSWORD=example"
  consul:
    image: consul
    ports:
      - 8500:8500
  consulator:
    image: lewispeckover/consulator
    command: "import /app/go-quick-consul.yml"
    depends_on:
      - consul
    volumes:
      - "./:/app"
    environment:
      - "CONSUL_HTTP_ADDR=consul:8500"
      - "CONSUL_HTTP_SSL=false"
secrets:
  password:
    file: ./secret.txt
